// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package example_1

// Injectors from wire.go:

func initEvent(msg string) Event {
	message := newMessage(msg)
	greeter := newGreeter(message)
	event := newEvent(greeter)
	return event
}
